#include "includes/codegen.hpp"

/*/////////////  REGISTER USED  ///////////////////////////////////
        int                    float
    integers → rax        floats → xmm0
    store    → mov        store  → movsd
    load     → mov        load   → movsd  
    add      → add        add    → addsd
    sub      → sub        sub    → subsd
    mul      → imul       mul    → mulsd
    div      → idiv       div    → divsd
*/////////////////////////////////////////////////////////////////

string currentLoopStart;    // for continue
string currentLoopEnd;      // for break

void CodeGenerator::emit(string line){
    output << "    " << line <<  "\n";
}

void CodeGenerator::emitLabel(string label) {
    output << label << ":\n";
}

string CodeGenerator::newLabel() {
    return ("label_" + to_string(labelCount++));
}

string CodeGenerator::newStringLabel(){
    return "str_" + to_string(stringCount++);
}

int CodeGenerator::typeSize(string type){
    if(type == "purnank") return 8;
    if(type == "dashamlav") return 8;
    if(type == "aksar") return 8;
    if(type == "tark") return 8;
    if (type == "aksarmala") return 8;
    return 8;
}

void CodeGenerator::generate(ProgramNode* node) {
    genProgram(node);
}

string CodeGenerator::getOutput(){
    stringstream final;
    final << "global _main\n\n";
    final << "section .data\n";
    final << dataSection.str();
    final << "\nsection .text\n";
    final << output.str();
    return final.str();
}

void CodeGenerator::writeToFile(string filename) {
    ofstream file(filename);
    file << getOutput();
    file.close();
}

void CodeGenerator::genProgram(ProgramNode* node) {
    output <<"; Generated by Sans Compiler \n\n";

    dataSection << "    dec_mult dq 100.0\n";

    // forward declare all functions
    for(auto* decl: node->declarations) {
        if (auto* f = dynamic_cast<FuncDeclNode*>(decl)){
            if (f->name != "mukhya")
                output << "global " << f->name << "\n";
        }
    }

    for (auto* decl : node->declarations){
        if (auto* f = dynamic_cast<FuncDeclNode*>(decl))
            genFuncDecl(f);
    }
}

bool CodeGenerator::isFloatNode(ASTNode* node){
    if (auto* lit = dynamic_cast<LiteralNode*>(node))
        return lit->type == TokenType::dashamlav_lit;
    if (auto* ident = dynamic_cast<IdentifierNode*>(node))
        return isFloatVar.count(ident->name) && isFloatVar[ident->name];
    if (auto* bin = dynamic_cast<BinaryOpNode*>(node))
        return isFloatNode(bin->left) || isFloatNode(bin->right);
    return false;
}

int CodeGenerator::calculateStackSize(BlockNode* body, vector<ParamNode*>& params){
    int size = 0;

    // params
    size += params.size() * 8;

    // count variables in block
    if  (!body) return size;
    for (auto* stmt : body->statements){
        if (auto* v = dynamic_cast<VarDeclNode*>(stmt)){
            if (v->type.substr(0,6) == "sarani") {
                // array - need to know element count
                if (auto* arr = dynamic_cast<ArrayLiteralNode*>(v->initializer))
                    size += arr->elements.size() * 8;
            } else {
                size += 8;
            }
        }
    }

    // add extra space for temporaries
    size += 64;

    return size;
}

void CodeGenerator::genFuncDecl(FuncDeclNode* node) {
    variables.clear();
    variableTypes.clear();
    stackOffset = 0;
    currentFunction = node->name;
    string funcName = (node->name == "mukhya") ? "_main" : node->name;
    
    output << "\n" << funcName << ":\n";

    emit("push rbp"); //save caller's base pointer
    emit("mov rbp, rsp"); // set our base pointer
    
    // calculate stack size needed
    int stackSize = calculateStackSize(node->body, node->params);

    // align to 16 bytes 
    if (stackSize % 16 != 0){
        stackSize += 16 - (stackSize % 16);
    }

    // minimum 32 bytes
    if (stackSize < 32) stackSize = 32;

    // reserve space for local variables
    // we use 128 bytes for now - improve later
    emit("sub rsp, " + to_string(stackSize)); // move stack pointer down
    
    // handle fucntion parameters
    // System V AMD64 calling convetion:
    // first 6 args come in: rdi,rsi,rdx,rcx,r8,r9
    vector<string> argRegs = {"rdi", "rsi", "rdx", "rcx", "r8", "r9"};
    for(int i = 0; i < node->params.size() && i < 6; i++){
        stackOffset += 8;
        variables[node->params[i]->name] = stackOffset;
        emit("mov [rbp-" + to_string(stackOffset) + "], " + argRegs[i]);
    }

    // generate function body
    genBlock(node->body);

}

void CodeGenerator::genBlock(BlockNode* node) {
    if (!node) return;

    // generate each statement in the block
    for (auto* stmt : node->statements){
        genStatement(stmt);
    }
}

void CodeGenerator::genStatement(ASTNode* node) {
    if (!node) return;

    if (auto* n = dynamic_cast<VarDeclNode*>(node))             genVarDecl(n);
    else if (auto* n = dynamic_cast<AssignNode*>(node))         genAssign(n);
    else if (auto* n = dynamic_cast<PrintNode*>(node))          genPrint(n);
    else if (auto* n = dynamic_cast<InputNode*>(node))          genInput(n);
    else if (auto* n = dynamic_cast<IfNode*>(node))             genIf(n);
    else if (auto* n = dynamic_cast<WhileNode*>(node))          genWhile(n);
    else if (auto* n = dynamic_cast<ForNode*>(node))            genFor(n);
    else if (auto* n = dynamic_cast<ReturnNode*>(node))         genReturn(n);
    else if (auto* n = dynamic_cast<BreakNode*>(node))          genBreak(n);
    else if (auto* n = dynamic_cast<ContinueNode*>(node))       genContinue(n);
    else if (auto* n = dynamic_cast<ExitNode*>(node))           genExit(n);
    else if (auto* n = dynamic_cast<FuncCallNode*>(node))       genFuncCall(n);
    else if (auto* n = dynamic_cast<UnaryOpNode*>(node))        genUnaryOp(n);
    else if (auto* n = dynamic_cast<BinaryOpNode*>(node))       genBinaryOp(n);
    else if (auto* n = dynamic_cast<FuncDeclNode *>(node))      genFuncDecl(n);
    else if (auto* n = dynamic_cast<ArrayAccessNode*>(node))    genArrayAccess(n);
    else if (auto* n = dynamic_cast<NewNode*>(node))            genNewExpr(n);
    else if (auto* n = dynamic_cast<FreeNode*>(node))           genFreeStmt(n);
    else if (auto* n = dynamic_cast<SwitchNode*>(node))         genSwitch(n);
}

void CodeGenerator::genExpr(ASTNode* node) {
    if (!node) return;

    if (auto* n = dynamic_cast<LiteralNode*>(node))
        genLiteral(n);
    else if (auto* n = dynamic_cast<IdentifierNode*>(node))
        genIdentifier(n);
    else if (auto* n = dynamic_cast<BinaryOpNode*>(node))
        genBinaryOp(n);
    else if (auto* n = dynamic_cast<UnaryOpNode*>(node))
        genUnaryOp(n);
    else if (auto* n = dynamic_cast<FuncCallNode*>(node))
        genFuncCall(n);
    else if (auto* n = dynamic_cast<ArrayLiteralNode*>(node))
        genArrayLiteral(n);
    else if (auto* n = dynamic_cast<ArrayAccessNode*>(node))  
        genArrayAccess(n);
    else if (auto* n = dynamic_cast<NewNode*>(node))
        genNewExpr(n);
}

void CodeGenerator::genLiteral(LiteralNode* node) {
    if (node->type == TokenType::purnank_lit){
        // integer Literal
        emit("mov rax, " + node->value);
    }
    else if (node->type == TokenType::satya){
        //boolean true = 1
        emit("mov rax, 1");
    }
    else if (node->type == TokenType::asatya){
        //boolean true = 0
        emit("mov rax, 0");
    }
    else if (node->type == TokenType::aksarmala_lit){
        //string literal - need to store in .data and load address
        string label = newStringLabel();
        dataSection << "   " << label << " db \"" << node->value << "\", 0\n";
        emit("lea rax, [rel " + label + "]");
    }
    else if (node->type == TokenType::dashamlav_lit) {
        string label = newLabel();
        dataSection << "    " << label << " dq " << node->value << "\n";
        emit("movsd xmm0, [rel " + label + "]"); 
        // leave result of xmm0 for float operations 
    }
    else if (node->type == TokenType::aksar_lit) {
        // store ASCII value of character
        char ch = node->value[0];
        emit("mov rax, " + to_string((int)ch));
    }

}

void CodeGenerator::genIdentifier(IdentifierNode* node) {
    // look up where this variable lives on stack
    auto it = variables.find(node->name);
    if (it == variables.end()){
        cerr << "[CodeGen Error] Undefined variable: " << node->name << endl;
        return;
    }

    int offset = it->second;

    if (isFloatVar.count(node->name) && isFloatVar[node->name]){
        emit("movsd xmm0, [rbp-"+ to_string(offset) +"]");
    } else {
        // load value from stack into rax
        emit("mov rax, [rbp-" + to_string(offset) + "]");
    }
}

void CodeGenerator::genVarDecl(VarDeclNode* node) {

    variableTypes[node->varName] = node->type;

    int size = typeSize(node->type);
    stackOffset += size;
    variables[node->varName] = stackOffset;

    if (node->type == "dashamlav") {
        isFloatVar[node->varName] = true;
        if (node->initializer) {
            genExpr(node->initializer);
            // result in xmm0 
            emit("movsd [rbp-"+ to_string(stackOffset) + "], xmm0");
        } else {
            emit("pxor xmm0, xmm0");     // zero
            emit("movsd [rbp-" + to_string(stackOffset) + "], xxm0");
        }
        return;
    }

    if (node->type.substr(0,6) == "sarani") {
        // array declaration
        if (node->initializer) {
            if (auto* arr = dynamic_cast<ArrayLiteralNode*>(node->initializer)) {
                int count = arr->elements.size();
                stackOffset += count * 8;
                int arrayBase = stackOffset;

                // store each element 
                for (int i = 0; i < arr->elements.size(); i++) {
                    genExpr(arr->elements[i]);
                    int elemOffset = arrayBase - (i * 8);
                    emit("mov [rbp-" + to_string(elemOffset) + "], rax");
                }

                // store base address in variable map
                variables[node->varName] = arrayBase;
            }
        }
        return;
    }

    // if there's an initializer, evaluate and store it
    if (node->initializer) {
        // evaluate expression - result goes into rax
        genExpr(node->initializer);
        //store rax value onto stack at variable's location
        emit("mov [rbp-" + to_string(stackOffset) + "], rax");
    } else {
        // no initalizer - deafult to 0
        emit("mov qword [rbp-" + to_string(stackOffset) + "], 0");
    }
}

void CodeGenerator::genAssign(AssignNode* node) {
    // evaluate right side - result goes into rax
    genExpr(node->value);

    //find where variable lives on stack
    auto it = variables.find(node->name);
    int offset = it->second;

    if (isFloatVar.count(node->name) && isFloatVar[node->name]) {
        if (node->op == TokenType::sthapna) {
            emit("movsd [rbp-" + to_string(offset) +"], xmm0");
        } else if (node->op == TokenType::yoga_sthapana){
            emit("movsd xmm1,[rbp-" + to_string(offset) + "]");
            emit("addsd xmm1, xmm0");
            emit("movsd [rbp-" + to_string(offset) +"], xmm1");
        } else if (node->op == TokenType::viyoga_sthapana){
            emit("movsd xmm1,[rbp-" + to_string(offset) + "]");
            emit("subsd xmm1, xmm0");
            emit("movsd [rbp-" + to_string(offset) +"], xmm1");
        } else if (node->op == TokenType::gunan_sthapana){
            emit("movsd xmm1,[rbp-" + to_string(offset) + "]");
            emit("mulsd xmm1, xmm0");
            emit("movsd [rbp-" + to_string(offset) +"], xmm1");
        } else if (node->op == TokenType::bhaga_sthapana){
            emit("movsd xmm1,[rbp-" + to_string(offset) + "]");
            emit("divsd xmm1, xmm0");
            emit("movsd [rbp-" + to_string(offset) +"], xmm1");
        }
        return;
    }


    if (it == variables.end()) {
        cerr << "[CodeGen Error] Undefined variable: " << node->name << endl;
        return;
    }

    // handle compound assigment operators
    if (node->op == TokenType::sthapna) {
        // x = expr -> just store rax
        emit("mov [rbp-" + to_string(offset) + "], rax");
    }
    else if (node->op == TokenType::yoga_sthapana) {
        // x += expr
        emit("mov rbx, [rbp-"+ to_string(offset) + "]");
        emit("add rbx, rax");
        emit("mov [rbp-"+ to_string(offset) + "], rbx");

    }else if (node->op == TokenType::viyoga_sthapana) {
        // x -= expr
        emit("mov rbx, [rbp-"+ to_string(offset) + "]");
        emit("sub rbx, rax");
        emit("mov [rbp-"+ to_string(offset) + "], rbx");

    }else if (node->op == TokenType::gunan_sthapana) {
        // x *= expr
        emit("mov rbx, [rbp-"+ to_string(offset) + "]");
        emit("imul rbx, rax");
        emit("mov [rbp-"+ to_string(offset) + "], rbx");
    }
    else if (node->op == TokenType::bhaga_sthapana) {
        // x /= expr
        emit("add rbx, rax");   // save divisor
        emit("mov rax, [rbp-"+ to_string(offset) + "]");
        emit("cqo");            // sign extend rax into rdx:rax
        emit("idiv rbx");       // rax = rax / rbx 
        emit("mov [rbp-"+ to_string(offset) + "], rax");
    }else if (node->op == TokenType::shesh_sthapana) {
        // x %= expr
        emit("add rbx, rax");   //save divisor
        emit("mov rax, [rbp-"+ to_string(offset) + "]");
        emit("cqo");            // sign extend
        emit("idiv rbx");       // remainder in rdx
        emit("mov [rbp-"+ to_string(offset) + "], rbx");
    }
}

void CodeGenerator::genBinaryOp(BinaryOpNode* node) {

    bool floatOp = isFloatNode(node->left) || isFloatNode(node->right);

    if (floatOp) {
        // evalutate left -> xmm0
        genExpr(node->left);
        emit("movsd [rbp-128], xmm0");      // save left temporarily

        // evluate right -> xmm0
        genExpr(node->right);
        emit("movsd xmm1, xmm0");           // xmm1 = right

        // restore left
        emit("movsd xmm0, [rbp-128]");      // xmm0 = left

        switch (node->op) {
            //arithmetic
            case TokenType::yoga:
                emit("addsd xmm0, xmm1");
                break;
    
            case TokenType::viyoga:
                emit("subsd xmm0, xmm1");
                break;
    
            case TokenType::gunan:
                emit("mulsd xmm0, xmm1");
                break;
            
            case TokenType::bhaga:
                emit("divsd xmm0, xmm1");
                break;

            // comparison -> result in rax
            case TokenType::adhik:
            case TokenType::sym_adhik: 
                emit("ucomisd xmm0, xmm1");
                emit("seta al");    // al = 1 if xmm0 > xmm1
                emit("movzx rax, al"); // zero extend al to rax
                break;
            
            case TokenType::nyun:
            case TokenType::sym_nyun:
                emit("ucomisd xmm0, xmm1");
                emit("setb al");
                emit("movzx rax, al");
                break;
            
            case TokenType::sam:
            case TokenType::sym_sam:
                emit("cmp rax, rbx");
                emit("setne al");
                emit("movzx rax, al");
                break;
            default:
                break;
        }
        return;
    }

    // evaluate left side -> result in rax
    genExpr(node->left);
    emit("push rax");       // save left resut to stack

    // evaluate right side -> result in rax
    genExpr(node->right);
    emit("mov rbx, rax");

    // restore left into rax
    emit("pop rax");

    // now: rax = left, rbx = right
    // perform operation

    switch (node->op) {
        //arithmetic
        case TokenType::yoga:
            emit("add rax, rbx");
            break;

        case TokenType::viyoga:
            emit("sub rax, rbx");
            break;

        case TokenType::gunan:
            emit("imul rax, rbx");
            break;
        
        case TokenType::bhaga:
            emit("cpo");
            emit("idiv rbx");
            //resut in rax
            break;
        case TokenType::shesh:
            emit("cqo");
            emit("idiv rbx");
            emit("mov rax, rdx"); // remainder in rdx -> move to rax
            break;
        
        // comparison operators -> result is 0 or 1 in rax
        case TokenType::adhik:
        case TokenType::sym_adhik: 
            emit("cmp rax, rbx");
            emit("setg al");    // al = 1 if rax > rbx
            emit("movzx rax, al"); // zero extend al to rax
            break;
        
        case TokenType::nyun:
        case TokenType::sym_nyun:
            emit("cmp rax,rbx");
            emit("setl al");
            emit("movzx rax, al");
            break;

        case TokenType::asam:
        case TokenType::sym_asam:
            emit("cmp rax, rbx");
            emit("setne al");
            emit("movzx rax, al");
            break;
        
        case TokenType::adhik_sam:
        case TokenType::sym_adhik_sam:
            emit("cmp rax, rbx");
            emit("setge al");
            emit("movzx rax, al");
            break;

        case TokenType::nyun_sam:
        case TokenType::sym_nyun_sam:
            emit("cmp rax, rbx");
            emit("setle al");
            emit("movzx rax, al");
         
        // Logical Operators
        case TokenType::tatha: // && (AND)
            emit("and rax, rbx");
            break;
        
        case TokenType::va:
            emit("or rax, rbx");

        default:
            cerr << "[CodeGen Error] Unkown binary operator" << endl;
            break;
    }

}

void CodeGenerator::genPrint(PrintNode* node) { 
    // evaluate expression - result in rax
    genExpr(node->value);


    if (auto* ident = dynamic_cast<IdentifierNode*>(node->value)) {
        if (isFloatVar.count(ident->name) && isFloatVar[ident->name]) {
            int offset = variables[ident->name];
            // print float
            // conver to string manually
            emit("movsd xmm0, [rbp-" + to_string(offset) + "]");

            // save full float value
            emit("movsd [rbp-128], xmm0");

            // get integer part
            emit("cvttsd2si r12, xmm0");            // r12 = integer part

            // print integer part using exisiting int print
            emit("mov rax, r12");
            emit("mov r13, 0");
            emit("cmp r12, 0");
            string notNeg = newLabel();
            emit("jge " + notNeg);
            emit("mov r13, 1");
            emit("neg r12");
            emitLabel(notNeg);
            emit("sub rsp, 32");
            emit("mov r10, 0");
            emit("push rdx");                       
            string digitLoop = newLabel();
            emitLabel(digitLoop);
            emit("mov rax, r12");
            emit("mov rbx, 10");
            emit("cqo");
            emit("idiv rbx");
            emit("add rdx, 48");
            emit("mov [rsp + r10], dl");
            emit("inc r10");
            emit("mov r12, rax");
            emit("cmp rax, 0");
            emit("jne " + digitLoop);
            string skipMinus = newLabel();
            emit("mov r8, 0");
            emit("mov r9, r10");
            emit("dec r9");
            string revLoop = newLabel();
            string revDone = newLabel();
            emitLabel(revLoop);
            emit("cmp r8, r9");
            emit("jge " + revDone);
            emit("mov al, [rsp + r8]");
            emit("mov bl, [rsp + r9]");
            emit("mov [rsp + r8], bl");
            emit("mov [rsp + r9], al");
            emit("inc r8");
            emit("dec r9");
            emit("jmp " + revLoop);
            emitLabel(revDone);
            emit("mov rax, 0x2000004");
            emit("mov rdi, 1");
            emit("lea rsi, [rsp]");
            emit("mov rdx, r10");
            emit("syscall");
            emit("pop rdx");
            emit("add rsp, 32");


            // print interger part first (reuse existing int print)
            // ... use existing integer print code

            // print decimal point
            string dotLabel = newStringLabel();
            dataSection << "    " << dotLabel << " db \".\", 0\n";
            emit("lea rsi, [rel " + dotLabel + "]");
            emit("mov rdi, 1");
            emit("mov rdx, 1");
            emit("mov rax, 0x2000004");
            emit("syscall");
            
            // get decimal part
            emit("movsd xmm0, [rbp-128]");
            emit("cvttsd2si rax, xmm0");
            emit("cvtsi2sd xmm1, rax"); 
            emit("subsd xmm0, xmm1");               // xmm0 = decimal part only
            emit("mulsd xmm0, [rel dec_mult]");     // multiply by 100
            emit("cvttsd2si r12, xmm0");            // rax = decimal digits
            
            // print decimal digits
            emit("mov rax, r12");
            emit("mov r13, 0");
            emit("sub rsp, 32");
            emit("mov r10, 0");
            emit("push rdx");
            string dDigitLoop = newLabel();
            emitLabel(dDigitLoop);
            emit("mov rax, r12");
            emit("mov rbx, 10");
            emit("cqo");
            emit("idiv rbx");
            emit("add rdx, 48");
            emit("mov [rsp + r10], dl");
            emit("inc r10");
            emit("mov r12, rax");
            emit("cmp rax, 0");
            emit("jne " + dDigitLoop);
            emit("mov r8, 0");
            emit("mov r9, r10");
            emit("dec r9");
            string dRevLoop = newLabel();
            string dRevDone = newLabel();
            emitLabel(dRevLoop);
            emit("cmp r8, r9");
            emit("jge " + dRevDone);
            emit("mov al, [rsp + r8]");
            emit("mov bl, [rsp + r9]");
            emit("mov [rsp + r8], bl");
            emit("mov [rsp + r9], al");
            emit("inc r8");
            emit("dec r9");
            emit("jmp " + dRevLoop);
            emitLabel(dRevDone);

            // add newline
            emit("mov byte [rsp + r10], 10");
            emit("inc r10");
            emit("mov rax, 0x2000004");
            emit("mov rdi, 1");
            emit("lea rsi, [rsp]");
            emit("mov rdx, r10");
            emit("syscall");
            emit("pop rdx");
            emit("add rsp, 32");
            return;
        }
        
        if(variableTypes.count(ident->name) && variableTypes[ident->name] == "aksar") {
            emit("sub rsp, 4");
            emit("mov [rsp], rax");         // store char temporarily
            emit("mov byte [rsp+1], 10");     // newline after char
            emit("mov rax, 0x2000004");
            emit("mov rdi, 1");
            emit("mov rsi, rsp");         // address of char
            emit("mov rdx, 2");                 // 1 char + newLine
            emit("syscall");
            emit("add rsp, 4");
            return;
        }
    
        auto typeIt = variableTypes.find(ident->name);
        if (typeIt != variableTypes.end() && typeIt->second == "aksarmala") {
            // print as string
            emit("mov rsi, rax");
            emit("mov rdi, 1");
            emit("mov rdx, 0");
            emit("mov rcx, rax");
            string lenLoop = newLabel();
            string lenDone = newLabel();
            emitLabel(lenLoop);
            emit("cmp byte [rcx], 0");
            emit("je " + lenDone);
            emit("inc rdx");
            emit("inc rcx");
            emit("jmp " + lenLoop);
            emitLabel(lenDone);
            emit("mov byte [rcx], 10");
            emit("inc rdx");
            emit("mov rax, 0x2000004");
            emit("mov rdi, 1");
            emit("syscall");
            return;
        }
        
    }

    // check what type were printing
    if (auto* lit = dynamic_cast<LiteralNode*>(node->value)) {

        if (lit->type == TokenType::aksar_lit){
            string label = newStringLabel();
            dataSection << "    " << label << " db " << to_string((int)lit->value[0]) << ", 10, 0\n";
            emit("mov rax, 0x2000004");
            emit("mov rdi, 1");
            emit("lea rsi, [rel " + label + "]");
            emit("mov rdx, 2");
            emit("syscall");
            return;
        }

        // printing a string literal
        // rax already has the address from genLiteral
        emit("mov rsi, rax");       // rsi = string address
        emit("mov rdi, 1");         // stdout
        // calculate string length
        emit("mov rdx, 0");         // length counter = 0
        emit("mov rcx, rax");       // rcx = string address
        string lenLoop = newLabel();
        string lenDone = newLabel();
        emitLabel(lenLoop);
        emit("cmp byte [rcx], 0");  // check null terminator
        emit("je " + lenDone);      // if 0 -> done counting
        emit("inc rdx");            // length++
        emit("inc rcx");            // move to next char
        emit("jmp " + lenLoop);      // loop
        emitLabel(lenDone);
        emit("mov byte [rcx], 10");     // store newline \n
        emit("inc rdx");                // include newline in length
        emit("mov rax, 0x2000004");
        emit("mov rdi, 1");             // ← add this line too
        emit("syscall");
        return;
    }   

    // printing identifier or expression (int)
    // need to convert integer to string first
    string printDone = newLabel();

    // save the number
    emit("mov r12, rax");           // r12 = number to print
    
    //handle negative number
    emit("mov r13, 0");             // r13 = negative flag
    emit("cmp r12, 0");
    string notNeg = newLabel();
    emit("jge " + notNeg);
    emit("mov r13, 1");             // set negative falg
    emit("neg r12");                // make positive
    emitLabel(notNeg);

    // convert integer to string
    // build string backwards on stack
    emit("sub rsp, 32");            // temp buffer on stack
    emit("mov r10, 0");             // digit count
    emit("push rdx");
    // emit("lea rdi, [rsp]");         // buffer pointer
    
    string digitLoop = newLabel();
    string digitDone = newLabel();

    emitLabel(digitLoop);
    emit("mov rax,r12");
    emit("mov rbx, 10");
    emit("cqo");
    emit("idiv rbx");               // rax = rax/10  , rdx = rax % 10
    emit("add rdx, 48");            // convert to ASCII ("0" = 48)
    emit("mov [rsp + r10], dl");      // store digit
    emit("inc r10");                // digit count++
    emit("mov r12, rax");           // remaining number
    emit("cmp rax, 0"); 
    emit("jne " + digitLoop);       // loop until 0
    
    // add minus sign if negative
    string skipMinus = newLabel();
    emit("cmp r13, 0");
    emit("je " + skipMinus);
    emit("mov byte [rsp+r10], 45");
    emit("inc r10");
    emitLabel(skipMinus);

    // reverse the string 
    emit("mov r8, 0");
    emit("mov r9, r10");
    emit("dec r9");

    string revLoop = newLabel();
    string revDone = newLabel();
    emitLabel(revLoop);
    emit("cmp r8, r9");
    emit("jge " + revDone);
    emit("mov al, [rsp + r8]");
    emit("mov bl, [rsp + r9]");
    emit("mov [rsp + r8], bl");
    emit("mov [rsp + r9], al");
    emit("inc r8");
    emit("dec r9");
    emit("jmp " + revLoop);
    emitLabel(revDone);

    // add newLine
    emit("mov byte [rsp + r10], 10");     // newline = ASCII 10
    emit("inc r10");

    // print using syscall
    emit("mov rax, 0x2000004");         // write syscall
    emit("mov rdi, 1");                 // stdout
    emit("lea rsi, [rsp]");             // buffer address
    emit("mov rdx, r10");               // length
    emit("syscall");

    // restore stack
    emit("add rsp, 32");
}

void CodeGenerator::genIf(IfNode* node) {
    string elseLabel = newLabel();      // label for else block 
    string endLabel = newLabel();       // label for end of if
    
    // evaluate condition - result in rax
    genExpr(node->condition);

    // if rax == 0 (false) -> jump to else
    emit("cmp rax, 0");
    emit("je " + elseLabel);

    // generate then block
    genBlock(node->thenBlock);

    // jump over else block
    emit("jmp " + endLabel);

    // else label
    emitLabel(elseLabel);

    // generate else block if exists
    if(node->elseBlock){
        genBlock(node->elseBlock);
    }

    // end label
    emitLabel(endLabel);
}

void CodeGenerator::genWhile(WhileNode* node) {
    string loopStart = newLabel();      // top of Loop
    string loopEnd = newLabel();        // exit Loop
    

    currentLoopEnd   = loopEnd;
    currentLoopStart = loopStart;
    
    //loop start label
    emitLabel(loopStart);

    // evaluate condtion - result in rax
    genExpr(node->condition);

    // if false -> exit Loop
    emit("cmp rax, 0");
    emit("je " + loopEnd);

    // generate loop body
    genBlock(node->body);

    // jump back to top
    emit("jmp " + loopStart);

    // loop end label
    emitLabel(loopEnd);
}

void CodeGenerator::genFor(ForNode* node) {
    if(node->isRange){
        // Style 1 - krute 1 : 0 se 10

        string loopStart = newLabel();
        string loopEnd = newLabel();

        currentLoopEnd   = loopEnd;
        currentLoopStart = loopStart;

        // allocate loop variables on stack
        stackOffset += 8;
        variables[node->var] = stackOffset;

        // initialize loop variable with from value
        genExpr(node->from);
        emit("mov [rbp-" + to_string(stackOffset) +"], rax");

        //loop start
        emitLabel(loopStart);

        // load i, compare with to value
        emit("mov rax, [rbp-"+ to_string(stackOffset) +"]");
        emit("push rax");
        genExpr(node->to);
        emit("mov rbx, rax");
        emit("pop rax");
        emit("cmp rax, rbx");
        emit("jge " + loopEnd);


        // genrate body
        genBlock(node->body);

        // increment i
        emit("mov rax, [rbp-" + to_string(stackOffset) +"]");
        emit("inc rax");
        emit("mov [rbp-" + to_string(stackOffset) +"], rax");

        // jump back to top
        emit("jmp " + loopStart);
        emitLabel(loopEnd);

        // remove loop var from scope
        variables.erase(node->var);
    } else {
        // style 2 - krute (i prunank = 0; i nyun 10; i++)

        string loopStart = newLabel();
        string loopEnd = newLabel();

        // generate init - e.g i purnank = 0
        if (node->from) genStatement(node->from);

        // generate start
        emitLabel(loopStart);

        // evaluate condition
        if (node->to) {
            genExpr(node->to);
            emit("cmp rax, 0");
            emit("je " + loopEnd);      // if false -> exit
        }

        // generate body
        genBlock(node->body);

        // generate update - e.g. i++
        if (node->update) genExpr (node->update);

        // jump back to top
        emit("jmp " + loopStart);
        emitLabel(loopEnd);
    }
}

void CodeGenerator::genReturn(ReturnNode* node) {
    if(node->value) {
        // evaluate return expression - result in rax
        genExpr(node->value);
        // rax already has return value
        // system v amd64: return values goes in rax
    }

    if (currentFunction == "mukhya") {
        // mukhya exits with syscall not ret
        emit("mov rax, 0x2000001");
        emit("mov rdi, 0");
        emit("syscall");
    } else {
        // regular function
        emit("mov rsp, rbp");
        emit("pop rbp");
        emit("ret");
    }

}

void CodeGenerator::genBreak(BreakNode* node) {
    emit("jmp " + currentLoopEnd);
}

void CodeGenerator::genContinue(ContinueNode* node) {
    emit("jmp " + currentLoopStart);
}

void CodeGenerator::genExit(ExitNode* node) {
    if (node->code) {
        genExpr(node->code);    // evaluate exit code -> rax
        emit("mov rdi, rax");   // exit code in rdi
    } else {
        emit("mov rdi, 0");     // default exit code 0
    }
    emit("mov rax, 0x2000001"); // exit syscall
    emit("syscall");
}

void CodeGenerator::genFuncCall(FuncCallNode* node) {
    // System V AMD64 calling convention
    // first 6 args go in registers:
    vector<string> argRegs = {"rdi", "rsi", "rdx", "rcx", "r8", "r9"};
    vector<string> floatRegs = {"xmm0","xmm1","xmm2","xmm3"};

    int intArgCount = 0;
    int floatArgCount = 0;

    for (int i =0 ; i < node->args.size(); i++){
        genExpr(node->args[i]);
        if(isFloatNode(node->args[i])){
            emit("movsd [rsp-" + to_string((i+1)*8) + "]");
        } else {
            emit ("push rax");
        }
    }

    // load into registers
    for (int i = node->args.size()-1; i >= 0; i--) {
        if (isFloatNode(node->args[i])){
            emit("movsd xmm" + to_string(floatArgCount++) + ", [rsp" + to_string((i+1)*8) +"]");
        } else {
            emit("pop " + argRegs[intArgCount++]);
        }
    }

    // save registers that might be in use
    emit("push r12");
    emit("push r13");

    // evaluate each argument and store temporarily on stack
    // then load into correct registers
    vector<int> argOffsets;

    for (int i = 0; i < node->args.size(); i++) {
        genExpr(node->args[i]);         // result in rax
        emit("push rax");               // save on stack temporarily
        argOffsets.push_back(i);    
    }
    
    // load args froms stack into registers (reverse order)
    for (int i = 0; i < node->args.size(); i++){
        if (i < 6) {
            emit("pop " + argRegs[i]);
        }else{
            // more than 6 args -. push onto stack (already there)
            break;
        }
    }

    // align stack to 16 bytes (Mac requirements)
    emit("mov r15, rsp");
    emit("and rsp, -16");

    // call the function
    emit("call " + node->funcName);

    emit("mov rsp, r15");
    // result is in rax after call
    emit("pop r13");
    emit("pop r12");
}

void CodeGenerator::genUnaryOp(UnaryOpNode* node) {
    cerr << "[DEBUG] genUnaryOp called postfix: " 
         << node->postfix << endl;
    if (node->postfix){
        // x++ or x--
        // need to get variable's address to modify it
        if (auto* ident = dynamic_cast<IdentifierNode*>(node->operand)){
            auto it = variables.find(ident->name);
            if (it ==  variables.end()){
                cerr << "[CodeGen Error] Undefined Variables: " << ident->name << endl;
                return;
            }
            int offset = it->second;

            // load current value
            emit("mov rax, [rbp-" + to_string(offset) + "]");

            if (node->op == TokenType::vriddhi){
                // x++
                emit("inc rax");             // increment
                emit("mov [rbp-"+ to_string(offset) + "], rax"); // store
                
            } else if(node->op == TokenType::kshaya){
                // x--
                emit("dec rax");             // increment
                emit("mov [rbp-"+ to_string(offset) + "], rax"); // store
            } 
        }
    } else {
        // prefix operator: !flag -x ++x --x
        if (node->op == TokenType::vriddhi) {
            // ++x
            if (auto* ident = dynamic_cast<IdentifierNode*>(node->operand)) {
                int offset = variables[ident->name];
                emit("mov rax, [rbp-" + to_string(offset) + "]");
                emit("inc rax");
                emit("mov [rbp-"+ to_string(offset) +"], rax");
            }
        }else if (node->op == TokenType::kshaya) {
            
            if (auto* ident = dynamic_cast<IdentifierNode*>(node->operand)) {
                int offset = variables[ident->name];
                emit("mov rax, [rbp-" + to_string(offset) + "]");
                emit("dec rax");
                emit("mov [rbp-"+ to_string(offset) +"], rax");
            }
        }else if (node->op == TokenType::viyoga) {
            // -x -> negate
            genExpr(node->operand);
            emit("neg rax");
        }else if (node->op == TokenType::na){
            // !x -> logical not
            genExpr(node->operand);
            emit("cmp rax, 0");
            emit("sete al");
            emit("movzx rax, al");
        }
    }
}

void CodeGenerator::genArrayLiteral(ArrayLiteralNode* node) {
    // allocate space for array on stack
    // each element takes 8 bytes
    int arraySize = node->elements.size() * 8;
    stackOffset += arraySize;
    int arrayBase = stackOffset;

    // store each element
    for (int i = 0; i < node->elements.size(); i++){
        genExpr(node->elements[i]);
        int elemOffset = arrayBase - (i * 8);
        emit("mov [rbp-"+ to_string(elemOffset) +"], rax");
    }

    // return address of first element in rax
    emit("lea rax, [rbp-" + to_string(arrayBase) + "]");
}

void CodeGenerator::genArrayAccess(ArrayAccessNode* node) {
    // find arrau base address
    auto it = variables.find(node->name);
    if (it == variables.end()){
        cerr << "[CodeGen Error] Undefined array: " << node->name << endl;
        return;
    }
    int baseOffset = it->second;

    // evaluate index - result in rax
    genExpr(node->index);

    // calculate element address
    // element address = base + (index * 8)
    emit("imul rax, 8");
    emit("mov rbx, rbp");
    emit("sub rbx, " + to_string(baseOffset));  // rbx = base address
    emit("sub rbx, rax");       // rbx = element address 

    if (node->value != nullptr){
        // assigment: arr[0] = 10
        emit("mov r14, rbx");               // save element address
        genExpr(node->value);           // evaluate value -> rax
        emit("mov [r14], rax");         // store value
    } else {
        // access: arr[i] mudraya
        emit("mov rax, [rbx]");
    }
}
void CodeGenerator::genInput(InputNode* node) {
    // find variable on stack
    auto it = variables.find(node->name);
    if (it == variables.end()){
        cerr << "[CodeGen Error] Undefined variable: " << node->name << endl;
        return;
    }
    int offset = it->second;

    // allocate buffer on stack for input
    emit("sub rsp, 32");        // 32 byte input buffer
    
    // read syscall
    emit("mov rax, 0x2000003");     // Mac read syscall
    emit("mov rdi, 0");             // stdin = 0
    emit("lea rsi, [rsp]");         // buffer address
    emit("mov rdx, 32");            // max byte to read
    emit("syscall");                // rax

    // convert string to integer
    // buffer at [rsp], length in rax
    emit("mov rcx, 0");             // result = 0
    emit("mov r8, 0");              // index = 0
    emit("mov r9, rax");            // r9 = length (bytes read)
    emit("dec r9");                 // ignore newline at end

    string convLoop = newLabel();
    string convDone = newLabel();

    emitLabel(convLoop);
    emit("cmp r8, r9");             // index == length?
    emit("jge " + convDone);        // yes -> done

    emit("movzx rax, byte [rsp+r8]");       // load character
    emit("sub rax, 48");                    // convert ASCII to digit
    emit("imul rcx, 10");                   // result *= 10
    emit("add rcx, rax");                   // result += digit
    emit("inc r8");                         // index++
    emit("jmp " + convLoop);

    emitLabel(convDone);

    // store result in variables
    emit("mov [rbp-" + to_string(offset) + "], rcx");

    // restore stack
    emit("add rsp, 32");
}

void CodeGenerator::genNewExpr(NewNode* node){
    // allocate memory on heap using mmap syscall (Mac)
    // mmap (NULL, size, PROT_READ | PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0)

    int size = typeSize(node->type);

    emit("mov rax, 0x20000C5");         // mmap syscall (Mac)
    emit("mov rdi, 0");                 // addr = NULL (let OS choose)
    emit("mov rsi, " +to_string(size)); // size
    emit("mov rdx, 3");                 // PROT_READ | PROT_WRITE
    emit("mov r10, 0x1002");            // MAP_PRIVATE | MAP_ANONYMOUS
    emit("mov r8, -1");                 // fd = -1
    emit("mov r9, 0");                  // offset = 0         
    emit("syscall");                    // rax = pointer to allocated memory
    // rax now has the heap address
}

void CodeGenerator::genFreeStmt(FreeNode* node){
    // find variable holding the pointer
    auto it = variables.find(node->name);
    if (it == variables.end()){
        cerr << "[CodeGen Error] Undefined variable: " << node->name << endl;
        return;
    }
    int offset = it->second;

    // load pointer from variable
    emit("mov rdi, [rbp-"+ to_string(offset ) + "]");    // addres to free
    emit("mov rsi, 8");                                  // size (same as allocated)
    emit("mov rax, 0x2000049");                          // munmap syscall (Mac)
    emit("syscall");                                     // free the memory
}

void CodeGenerator::genSwitch(SwitchNode* node){
    // evaluate switch expressions - result in rax
    genExpr(node->expression);
    emit("mov r12, rax");                   // save switch value in r12

    string switchEnd = newLabel();
    vector<string> caseLabels;

    // generate label for each case
    for (int i = 0; i < node->cases.size(); i++){
        caseLabels.push_back(newLabel());
    }

    // generate comparisons
    for (int i = 0; i < node->cases.size(); i++){
        CaseNode* c = node->cases[i];

        if (c->value == nullptr) {
            // adya (default) - always jump to it
            emit("jmp " + caseLabels[i]);
        } else {
            // evaluate case value
            genExpr(c->value);
            emit("cmp r12, rax");               // compare switch value
            emit("je " + caseLabels[i]);        // if match -> jump to case
        }
    }

    // no case matched and no default -> jump to end
    emit("jmp " + switchEnd);

    // generate case bodies
    for (int i = 0; i < node->cases.size(); i++){
        emitLabel(caseLabels[i]);
        genBlock(node->cases[i]->body);
        emit("jmp " + switchEnd);           // viram -> jump to end
    }

    emitLabel(switchEnd);
}