#include "includes/codegen.hpp"


string currentLoopStart;    // for continue
string currentLoopEnd;      // for break

void CodeGenerator::emit(string line){
    output << "    " << line <<  "\n";
}

void CodeGenerator::emitLabel(string label) {
    output << label << ":\n";
}

string CodeGenerator::newLabel() {
    return ("label_" + to_string(labelCount++));
}

string CodeGenerator::newStringLabel(){
    return "str_" + to_string(stringCount++);
}

int CodeGenerator::typeSize(string type){
    if(type == "purnank") return 8;
    if(type == "dashamlav") return 8;
    if(type == "aksar") return 8;
    if(type == "tark") return 8;
    return 0;
}

void CodeGenerator::generate(ProgramNode* node) {
    genProgram(node);
}

string CodeGenerator::getOutput(){
    stringstream final;
    final << "global _main\n\n";
    final << "section .data\n";
    final << dataSection.str();
    final << "\nsection .text\n";
    final << output.str();
    return final.str();
}

void CodeGenerator::writeToFile(string filename) {
    ofstream file(filename);
    file << getOutput();
    file.close();
}

void CodeGenerator::genProgram(ProgramNode* node) {
    output <<"; Generated by Sans Compiler \n\n";

    // forward declare all functions
    for(auto* decl: node->declarations) {
        if (auto* f = dynamic_cast<FuncDeclNode*>(decl)){
            if (f->name != "mukhya")
                output << "global" << f->name << "\n";
        }
    }

    for (auto* decl : node->declarations){
        if (auto* f = dynamic_cast<FuncDeclNode*>(decl))
            genFuncDecl(f);
    }
}

void CodeGenerator::genFuncDecl(FuncDeclNode* node) {
    variables.clear();
    stackOffset = 0;

    string funcName = (node->name == "mukhya") ? "_main" : node->name;
    
    output << "\n" << funcName << ":\n";

    emit("push rbp"); //save caller's base pointer
    emit("mov rbp, rsp"); // set our base pointer
    
    // reserve space for local variables
    // we use 128 bytes for now - improve later
    emit("sub rsp, 128"); // move stack pointer down
    
    // handle fucntion parameters
    // System V AMD64 calling convetion:
    // first 6 args come in: rdi,rsi,rdx,rcx,r8,r9
    vector<string> argRegs = {"rdi", "rsi", "rdx", "rcx", "r8", "r9"};
    for(int i = 0; i < node->params.size() && i < 6; i++){
        stackOffset += 8;
        variables[node->params[i]->name] = stackOffset;
        emit("mov [rbp-" + to_string(stackOffset) + "], " + argRegs[i]);
    }

    // generate function body
    genBlock(node->body);

    // function epilogue - only for non-main void functions
    if (node->name == "mukhya") {
        emit("mov rax, 0x2000001");
        emit("mov rdi, 0");
        emit("syscall");
        // no ret here
    } else {
        emit("mov rsp, rbp");
        emit("pop rbp");
        emit("ret");
    }

}

void CodeGenerator::genBlock(BlockNode* node) {
    if (!node) return;

    // generate each statement in the block
    for (auto* stmt : node->statements){
        genStatement(stmt);
    }
}

void CodeGenerator::genStatement(ASTNode* node) {
    if (!node) return;

    if (auto* n = dynamic_cast<VarDeclNode*>(node))         genVarDecl(n);
    else if (auto* n = dynamic_cast<AssignNode*>(node))     genAssign(n);
    else if (auto* n = dynamic_cast<PrintNode*>(node))      genPrint(n);
    else if (auto* n = dynamic_cast<InputNode*>(node))      genInput(n);
    else if (auto* n = dynamic_cast<IfNode*>(node))         genIf(n);
    else if (auto* n = dynamic_cast<WhileNode*>(node))      genWhile(n);
    else if (auto* n = dynamic_cast<ForNode*>(node))        genFor(n);
    else if (auto* n = dynamic_cast<ReturnNode*>(node))     genReturn(n);
    else if (auto* n = dynamic_cast<BreakNode*>(node))      genBreak(n);
    else if (auto* n = dynamic_cast<ContinueNode*>(node))   genContinue(n);
    else if (auto* n = dynamic_cast<ExitNode*>(node))       genExit(n);
    else if (auto* n = dynamic_cast<FuncCallNode*>(node))   genFuncCall(n);
    else if (auto* n = dynamic_cast<UnaryOpNode*>(node))    genUnaryOp(n);
    else if (auto* n = dynamic_cast<BinaryOpNode*>(node))   genBinaryOp(n);
    else if (auto* n = dynamic_cast<FuncDeclNode *>(node))  genFuncDecl(n);
}

void CodeGenerator::genExpr(ASTNode* node) {
    if (!node) return;

    if (auto* n = dynamic_cast<LiteralNode*>(node))
        genLiteral(n);
    else if (auto* n = dynamic_cast<IdentifierNode*>(node))
        genIdentifier(n);
    else if (auto* n = dynamic_cast<BinaryOpNode*>(node))
        genBinaryOp(n);
    else if (auto* n = dynamic_cast<UnaryOpNode*>(node))
        genUnaryOp(n);
    else if (auto* n = dynamic_cast<FuncCallNode*>(node))
        genFuncCall(n);
}

void CodeGenerator::genLiteral(LiteralNode* node) {
    if (node->type == TokenType::purnank_lit){
        // integer Literal
        emit("mov rax, " + node->value);
    }
    else if (node->type == TokenType::satya){
        //boolean true = 1
        emit("mov rax, 1");
    }
    else if (node->type == TokenType::asatya){
        //boolean true = 0
        emit("mov rax, 0");
    }
    else if (node->type == TokenType::aksarmala_lit){
        //string literal - need to store in .data and load address
        string label = newStringLabel();
        dataSection << "   " << label << " db \"" << node->value << "\", 0\n";
        emit("lea rax, [rel " + label + "]");
    }
}

void CodeGenerator::genIdentifier(IdentifierNode* node) {
    // look up where this variable lives on stack
    auto it = variables.find(node->name);
    if (it == variables.end()){
        cerr << "[CodeGen Error] Undefined variable: " << node->name << endl;
        return;
    }

    int offset = it->second;

    // load value from stack into rax
    emit("mov rax, [rbp-" + to_string(offset) + "]");
}

void CodeGenerator::genVarDecl(VarDeclNode* node) {
    // calculate stack space needed
    int size = typeSize(node->type);
    stackOffset += size;

    // remember where the variable lives
    variables[node->varName] = stackOffset;
    
    // if there's an initializer, evaluate and store it
    if (node->initializer) {
        // evaluate expression - result goes into rax
        genExpr(node->initializer);
        //store rax value onto stack at variable's location
        emit("mov [rbp-" + to_string(stackOffset) + "], rax");
    } else {
        // no initalizer - deafult to 0
        emit("mov qword [rbp-" + to_string(stackOffset) + "], 0");
    }
}

void CodeGenerator::genAssign(AssignNode* node) {
    // evaluate right side - result goes into rax
    genExpr(node->value);

    //find where variable lives on stack
    auto it = variables.find(node->name);
    if (it == variables.end()) {
        cerr << "[CodeGen Error] Undefined variable: " << node->name << endl;
        return;
    }

    int offset = it->second;

    // handle compound assigment operators
    if (node->op == TokenType::sthapna) {
        // x = expr -> just store rax
        emit("mov [rbp-" + to_string(offset) + "], rax");
    }
    else if (node->op == TokenType::yoga_sthapana) {
        // x += expr
        emit("mov rbx, [rbp-"+ to_string(offset) + "]");
        emit("add rbx, rax");
        emit("mov [rbp-"+ to_string(offset) + "], rbx");

    }else if (node->op == TokenType::viyoga_sthapana) {
        // x -= expr
        emit("mov rbx, [rbp-"+ to_string(offset) + "]");
        emit("sub rbx, rax");
        emit("mov [rbp-"+ to_string(offset) + "], rbx");

    }else if (node->op == TokenType::gunan_sthapana) {
        // x *= expr
        emit("mov rbx, [rbp-"+ to_string(offset) + "]");
        emit("imul rbx, rax");
        emit("mov [rbp-"+ to_string(offset) + "], rbx");
    }
    else if (node->op == TokenType::bhaga_sthapana) {
        // x /= expr
        emit("add rbx, rax");   // save divisor
        emit("mov rax, [rbp-"+ to_string(offset) + "]");
        emit("cqo");            // sign extend rax into rdx:rax
        emit("idiv rbx");       // rax = rax / rbx 
        emit("mov [rbp-"+ to_string(offset) + "], rax");
    }else if (node->op == TokenType::shesh_sthapana) {
        // x %= expr
        emit("add rbx, rax");   //save divisor
        emit("mov rax, [rbp-"+ to_string(offset) + "]");
        emit("cqo");            // sign extend
        emit("idiv rbx");       // remainder in rdx
        emit("mov [rbp-"+ to_string(offset) + "], rbx");
    }
}

void CodeGenerator::genBinaryOp(BinaryOpNode* node) {
    // evaluate left side -> result in rax
    genExpr(node->left);
    emit("push rax");       // save left resut to stack

    // evaluate right side -> result in rax
    genExpr(node->right);
    emit("mov rbx, rax");

    // restore left into rax
    emit("pop rax");

    // now: rax = left, rbx = right
    // perform operation

    switch (node->op) {
        //arithmetic
        case TokenType::yoga:
            emit("add rax, rbx");
            break;

        case TokenType::viyoga:
            emit("sub rax, rbx");
            break;

        case TokenType::gunan:
            emit("imul rax,rbx");
            break;
        
        case TokenType::bhaga:
            emit("cpo");
            emit("idiv rbx");
            //resut in rax
            break;
        case TokenType::shesh:
            emit("cqo");
            emit("idiv rbx");
            emit("mov rax, rdx"); // remainder in rdx -> move to rax
            break;
        
        // comparison operators -> result is 0 or 1 in rax
        case TokenType::adhik:
        case TokenType::sym_adhik: 
            emit("cmp rax, rbx");
            emit("setg al");    // al = 1 if rax > rbx
            emit("movzx rax, al"); // zero extend al to rax
            break;
        
        case TokenType::nyun:
        case TokenType::sym_nyun:
            emit("cmp rax,rbx");
            emit("setl al");
            emit("movzx rax, al");
            break;

        case TokenType::asam:
        case TokenType::sym_asam:
            emit("cmp rax, rbx");
            emit("setne al");
            emit("movzx rax, al");
            break;
        
        case TokenType::adhik_sam:
        case TokenType::sym_adhik_sam:
            emit("cmp rax, rbx");
            emit("setge al");
            emit("movzx rax, al");
            break;

        case TokenType::nyun_sam:
        case TokenType::sym_nyun_sam:
            emit("cmp rax, rbx");
            emit("setle al");
            emit("movzx rax, al");
         
        // Logical Operators
        case TokenType::tatha: // && (AND)
            emit("and rax, rbx");
            break;
        
        case TokenType::va:
            emit("or rax, rbx");

        default:
            cerr << "[CodeGen Error] Unkown binary operator" << endl;
            break;
    }

}

void CodeGenerator::genPrint(PrintNode* node) {
    // evaluate expression - result in rax
    genExpr(node->value);

    // check what type were printing
    if (auto* lit = dynamic_cast<LiteralNode*>(node->value)) {
        // printing a string literal
        // rax already has the address from genLiteral
        emit("mov rsi, rax");       // rsi = string address
        emit("mov rdi, 1");         // stdout
        // calculate string length
        emit("mov rdx, 0");         // length counter = 0
        emit("mov rcx, rax");       // rcx = string address
        string lenLoop = newLabel();
        string lenDone = newLabel();
        emitLabel(lenLoop);
        emit("cmp byte [rcx], 0");  // check null terminator
        emit("je " + lenDone);      // if 0 -> done counting
        emit("inc rdx");            // length++
        emit("inc rcx");            // move to next char
        emit("jmp " + lenLoop);      // loop
        emitLabel(lenDone);
        emit("mov rax, 0x2000004"); // write syscall
        emit("syscall");
        return;
    }   

    // printing identifier or expression (int)
    // need to convert integer to string first
    string printDone = newLabel();

    // save the number
    emit("mov r12, rax");           // r12 = number to print
    
    //handle negative number
    emit("mov r13, 0");             // r13 = negative flag
    emit("cmp r12, 0");
    string notNeg = newLabel();
    emit("jge " + notNeg);
    emit("mov r13, 1");             // set negative falg
    emit("neg r12");                // make positive
    emitLabel(notNeg);

    // convert integer to string
    // build string backwards on stack
    emit("sub rsp, 32");            // temp buffer on stack
    emit("mov r10, 0");             // digit count
    emit("push rdx");
    // emit("lea rdi, [rsp]");         // buffer pointer
    
    string digitLoop = newLabel();
    string digitDone = newLabel();

    emitLabel(digitLoop);
    emit("mov rax,r12");
    emit("mov rbx, 10");
    emit("cqo");
    emit("idiv rbx");               // rax = rax/10  , rdx = rax % 10
    emit("add rdx, 48");            // convert to ASCII ("0" = 48)
    emit("mov [rsp + r10], dl");      // store digit
    emit("inc r10");                // digit count++
    emit("mov r12, rax");           // remaining number
    emit("cmp rax, 0"); 
    emit("jne " + digitLoop);       // loop until 0
    
    // add minus sign if negative
    string skipMinus = newLabel();
    emit("cmp r13, 0");
    emit("je " + skipMinus);
    emit("mov byte [rsp+r10], 45");
    emit("inc r10");
    emitLabel(skipMinus);

    // reverse the string 
    emit("mov r8, 0");
    emit("mov r9, r10");
    emit("dec r9");

    string revLoop = newLabel();
    string revDone = newLabel();
    emitLabel(revLoop);
    emit("cmp r8, r9");
    emit("jge " + revDone);
    emit("mov al, [rsp + r8]");
    emit("mov bl, [rsp + r9]");
    emit("mov [rsp + r8], bl");
    emit("mov [rsp + r9], al");
    emit("inc r8");
    emit("dec r9");
    emit("jmp " + revLoop);
    emitLabel(revDone);

    // add newLine
    emit("mov byte [rsp + r10], 10");     // newline = ASCII 10
    emit("inc r10");

    // print using syscall
    emit("mov rax, 0x2000004");         // write syscall
    emit("mov rdi, 1");                 // stdout
    emit("lea rsi, [rsp]");             // buffer address
    emit("mov rdx, r10");               // length
    emit("syscall");

    // restore stack
    emit("add rsp, 32");
}

void CodeGenerator::genIf(IfNode* node) {
    string elseLabel = newLabel();      // label for else block 
    string endLabel = newLabel();       // label for end of if
    
    // evaluate condition - result in rax
    genExpr(node->condition);

    // if rax == 0 (false) -> jump to else
    emit("cmp rax, 0");
    emit("je " + elseLabel);

    // generate then block
    genBlock(node->thenBlock);

    // jump over else block
    emit("jmp " + endLabel);

    // else label
    emitLabel(elseLabel);

    // generate else block if exists
    if(node->elseBlock){
        genBlock(node->elseBlock);
    }

    // end label
    emitLabel(endLabel);
}

void CodeGenerator::genWhile(WhileNode* node) {
    string loopStart = newLabel();      // top of Loop
    string loopEnd = newLabel();        // exit Loop
    

    currentLoopEnd   = loopEnd;
    currentLoopStart = loopStart;
    
    //loop start label
    emitLabel(loopStart);

    // evaluate condtion - result in rax
    genExpr(node->condition);

    // if false -> exit Loop
    emit("cmp rax, 0");
    emit("je " + loopEnd);

    // generate loop body
    genBlock(node->body);

    // jump back to top
    emit("jmp " + loopStart);

    // loop end label
    emitLabel(loopEnd);
}

void CodeGenerator::genFor(ForNode* node) {
    if(node->isRange){
        // Style 1 - krute 1 : 0 se 10

        string loopStart = newLabel();
        string loopEnd = newLabel();

        currentLoopEnd   = loopEnd;
        currentLoopStart = loopStart;

        // allocate loop variables on stack
        stackOffset += 8;
        variables[node->var] = stackOffset;

        // initialize loop variable with from value
        genExpr(node->from);
        emit("mov [rbp-" + to_string(stackOffset) +"], rax");

        //loop start
        emitLabel(loopStart);

        // load i, compare with to value
        emit("mov rax, [rbp-"+ to_string(stackOffset) +"]");
        emit("push rax");
        genExpr(node->to);
        emit("mov rbx, rax");
        emit("pop rax");
        emit("cmp rax, rbx");
        emit("jge " + loopEnd);


        // genrate body
        genBlock(node->body);

        // increment i
        emit("mov rax, [rbp-" + to_string(stackOffset) +"]");
        emit("inc rax");
        emit("mov [rbp-" + to_string(stackOffset) +"], rax");

        // jump back to top
        emit("jmp " + loopStart);
        emitLabel(loopEnd);

        // remove loop var from scope
        variables.erase(node->var);
    } else {
        // style 2 - krute (i prunank = 0; i nyun 10; i++)

        string loopStart = newLabel();
        string loopEnd = newLabel();

        // generate init - e.g i purnank = 0
        if (node->from) genStatement(node->from);

        // generate start
        emitLabel(loopStart);

        // evaluate condition
        if (node->to) {
            genExpr(node->to);
            emit("cmp rax, 0");
            emit("je " + loopEnd);      // if false -> exit
        }

        // generate body
        genBlock(node->body);

        // generate update - e.g. i++
        if (node->update) genExpr (node->update);

        // jump back to top
        emit("jmp " + loopStart);
        emitLabel(loopEnd);
    }
}

void CodeGenerator::genReturn(ReturnNode* node) {
    if(node->value) {
        // evaluate return expression - result in rax
        genExpr(node->value);
        // rax already has return value
        // system v amd64: return values goes in rax
    }

    // function epilogue 
    emit("mov rsp, rbp");       // restore stack pointer
    emit("pop rbp");            // restore base pointer
    emit("ret");                // return to caller
}

void CodeGenerator::genBreak(BreakNode* node) {
    emit("jmp " + currentLoopEnd);
}

void CodeGenerator::genContinue(ContinueNode* node) {
    emit("jmp " + currentLoopStart);
}

void CodeGenerator::genExit(ExitNode* node) {
    if (node->code) {
        genExpr(node->code);    // evaluate exit code -> rax
        emit("mov rdi, rax");   // exit code in rdi
    } else {
        emit("mov rdi, 0");     // default exit code 0
    }
    emit("mov rax, 0x2000001"); // exit syscall
    emit("syscall");
}

void CodeGenerator::genFuncCall(FuncCallNode* node) {
    // System V AMD64 calling convention
    // first 6 args go in registers:
    vector<string> argRegs = {"rdi", "rsi", "rdx", "rcx", "r8", "r9"};

    // save registers that might be in use
    emit("push r12");
    emit("push r13");

    // evaluate each argument and store temporarily on stack
    // then load into correct registers
    vector<int> argOffsets;

    for (int i = 0; i < node->args.size(); i++) {
        genExpr(node->args[i]);         // result in rax
        emit("push rax");               // save on stack temporarily
        argOffsets.push_back(i);    
    }
    
    // load args froms stack into registers (reverse order)
    for (int i = 0; i < node->args.size(); i++){
        if (i < 6) {
            emit("pop " + argRegs[i]);
        }else{
            // more than 6 args -. push onto stack (already there)
            break;
        }
    }

    // align stack to 16 bytes (Mac requirements)
    emit("and rsp, -16");

    // call the function
    emit("call " + node->funcName);

    // result is in rax after call
    emit("pop r13");
    emit("pop r12");
}

void CodeGenerator::genUnaryOp(UnaryOpNode* node) {
    if (node->postfix){
        // x++ or x--
        // need to get variable's address to modify it
        if (auto* ident = dynamic_cast<IdentifierNode*>(node->operand)){
            auto it = variables.find(ident->name);
            if (it ==  variables.end()){
                cerr << "[CodeGen Error] Undefined Variables: " << ident->name << endl;
                return;
            }
            int offset = it->second;

            // load current value
            emit("mov rax, [rbp-" + to_string(offset) + "]");

            if (node->op == TokenType::vriddhi){
                // x++
                emit("inc rax");             // increment
                emit("mov [rbp-"+ to_string(offset) + "], rax"); // store
                
            } else if(node->op == TokenType::kshaya){
                // x--
                emit("dec rax");             // increment
                emit("mov [rbp-"+ to_string(offset) + "], rax"); // store
            } 
        }
    } else {
        // prefix operator: !flag -x ++x --x
        if (node->op == TokenType::vriddhi) {
            // ++x
            if (auto* ident = dynamic_cast<IdentifierNode*>(node->operand)) {
                int offset = variables[ident->name];
                emit("mov rax, [rbp-" + to_string(offset) + "]");
                emit("inc rax");
                emit("mov [rbp-"+ to_string(offset) +"], rax");
            }
        }else if (node->op == TokenType::kshaya) {
            
            if (auto* ident = dynamic_cast<IdentifierNode*>(node->operand)) {
                int offset = variables[ident->name];
                emit("mov rax, [rbp-" + to_string(offset) + "]");
                emit("dec rax");
                emit("mov [rbp-"+ to_string(offset) +"], rax");
            }
        }else if (node->op == TokenType::viyoga) {
            // -x -> negate
            genExpr(node->operand);
            emit("neg rax");
        }else if (node->op == TokenType::na){
            // !x -> logical not
            genExpr(node->operand);
            emit("cmp rax, 0");
            emit("sete al");
            emit("movzx rax, al");
        }
    }
}

void CodeGenerator::genInput(InputNode* node) {}
void CodeGenerator::genArrayLiteral(ArrayLiteralNode* node) {}
void CodeGenerator::genArrayAccess(ArrayAccessNode* node) {}