global _main

section .data

section .text
; Generated by Sans Compiler 


_main:
    push rbp
    mov rbp, rsp
    sub rsp, 128
    mov rax, 5
    mov [rbp-8], rax
    mov rax, [rbp-8]
    inc rax
    mov [rbp-8], rax
    mov rax, [rbp-8]
    mov r12, rax
    mov r13, 0
    cmp r12, 0
    jge label_1
    mov r13, 1
    neg r12
label_1:
    sub rsp, 32
    mov r10, 0
    push rdx
label_2:
    mov rax,r12
    mov rbx, 10
    cqo
    idiv rbx
    add rdx, 48
    mov [rsp + r10], dl
    inc r10
    mov r12, rax
    cmp rax, 0
    jne label_2
    cmp r13, 0
    je label_4
    mov byte [rsp+r10], 45
    inc r10
label_4:
    mov r8, 0
    mov r9, r10
    dec r9
label_5:
    cmp r8, r9
    jge label_6
    mov al, [rsp + r8]
    mov bl, [rsp + r9]
    mov [rsp + r8], bl
    mov [rsp + r9], al
    inc r8
    dec r9
    jmp label_5
label_6:
    mov byte [rsp + r10], 10
    inc r10
    mov rax, 0x2000004
    mov rdi, 1
    lea rsi, [rsp]
    mov rdx, r10
    syscall
    add rsp, 32
    mov rax, [rbp-8]
    dec rax
    mov [rbp-8], rax
    mov rax, [rbp-8]
    mov r12, rax
    mov r13, 0
    cmp r12, 0
    jge label_8
    mov r13, 1
    neg r12
label_8:
    sub rsp, 32
    mov r10, 0
    push rdx
label_9:
    mov rax,r12
    mov rbx, 10
    cqo
    idiv rbx
    add rdx, 48
    mov [rsp + r10], dl
    inc r10
    mov r12, rax
    cmp rax, 0
    jne label_9
    cmp r13, 0
    je label_11
    mov byte [rsp+r10], 45
    inc r10
label_11:
    mov r8, 0
    mov r9, r10
    dec r9
label_12:
    cmp r8, r9
    jge label_13
    mov al, [rsp + r8]
    mov bl, [rsp + r9]
    mov [rsp + r8], bl
    mov [rsp + r9], al
    inc r8
    dec r9
    jmp label_12
label_13:
    mov byte [rsp + r10], 10
    inc r10
    mov rax, 0x2000004
    mov rdi, 1
    lea rsi, [rsp]
    mov rdx, r10
    syscall
    add rsp, 32
    mov rax, 10
    mov [rbp-16], rax
    mov rax, 2
    mov rbx, [rbp-16]
    imul rbx, rax
    mov [rbp-16], rbx
    mov rax, [rbp-16]
    mov r12, rax
    mov r13, 0
    cmp r12, 0
    jge label_15
    mov r13, 1
    neg r12
label_15:
    sub rsp, 32
    mov r10, 0
    push rdx
label_16:
    mov rax,r12
    mov rbx, 10
    cqo
    idiv rbx
    add rdx, 48
    mov [rsp + r10], dl
    inc r10
    mov r12, rax
    cmp rax, 0
    jne label_16
    cmp r13, 0
    je label_18
    mov byte [rsp+r10], 45
    inc r10
label_18:
    mov r8, 0
    mov r9, r10
    dec r9
label_19:
    cmp r8, r9
    jge label_20
    mov al, [rsp + r8]
    mov bl, [rsp + r9]
    mov [rsp + r8], bl
    mov [rsp + r9], al
    inc r8
    dec r9
    jmp label_19
label_20:
    mov byte [rsp + r10], 10
    inc r10
    mov rax, 0x2000004
    mov rdi, 1
    lea rsi, [rsp]
    mov rdx, r10
    syscall
    add rsp, 32
    mov rax, 1
    mov [rbp-24], rax
    mov rax, [rbp-24]
    cmp rax, 0
    sete al
    movzx rax, al
    mov [rbp-24], rax
    mov rax, [rbp-24]
    mov r12, rax
    mov r13, 0
    cmp r12, 0
    jge label_22
    mov r13, 1
    neg r12
label_22:
    sub rsp, 32
    mov r10, 0
    push rdx
label_23:
    mov rax,r12
    mov rbx, 10
    cqo
    idiv rbx
    add rdx, 48
    mov [rsp + r10], dl
    inc r10
    mov r12, rax
    cmp rax, 0
    jne label_23
    cmp r13, 0
    je label_25
    mov byte [rsp+r10], 45
    inc r10
label_25:
    mov r8, 0
    mov r9, r10
    dec r9
label_26:
    cmp r8, r9
    jge label_27
    mov al, [rsp + r8]
    mov bl, [rsp + r9]
    mov [rsp + r8], bl
    mov [rsp + r9], al
    inc r8
    dec r9
    jmp label_26
label_27:
    mov byte [rsp + r10], 10
    inc r10
    mov rax, 0x2000004
    mov rdi, 1
    lea rsi, [rsp]
    mov rdx, r10
    syscall
    add rsp, 32
    mov rsp, rbp
    pop rbp
    ret
    mov rax, 0x2000001
    mov rdi, 0
    syscall
