global _main

section .data
    dec_mult dq 100.0

section .text
; Generated by Sans Compiler 

global jodan

jodan:
    push rbp
    mov rbp, rsp
    sub rsp, 80
    mov [rbp-8], rdi
    mov [rbp-16], rsi
    mov rax, [rbp-8]
    push rax
    mov rax, [rbp-16]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov rsp, rbp
    pop rbp
    ret

_main:
    push rbp
    mov rbp, rsp
    sub rsp, 80
    mov rax, 1
    push rax
    mov rax, 2
    push rax
    pop rdi
    pop rsi
    push r12
    push r13
    mov rax, 1
    push rax
    mov rax, 2
    push rax
    pop rdi
    pop rsi
    mov r15, rsp
    and rsp, -16
    call jodan
    mov rsp, r15
    pop r13
    pop r12
    push rax
    mov rax, 3
    push rax
    pop rdi
    pop rsi
    push r12
    push r13
    mov rax, 1
    push rax
    mov rax, 2
    push rax
    pop rdi
    pop rsi
    push r12
    push r13
    mov rax, 1
    push rax
    mov rax, 2
    push rax
    pop rdi
    pop rsi
    mov r15, rsp
    and rsp, -16
    call jodan
    mov rsp, r15
    pop r13
    pop r12
    push rax
    mov rax, 3
    push rax
    pop rdi
    pop rsi
    mov r15, rsp
    and rsp, -16
    call jodan
    mov rsp, r15
    pop r13
    pop r12
    mov [rbp-8], rax
    mov rax, [rbp-8]
    mov r12, rax
    mov r13, 0
    cmp r12, 0
    jge label_1
    mov r13, 1
    neg r12
label_1:
    sub rsp, 32
    mov r10, 0
    push rdx
label_2:
    mov rax,r12
    mov rbx, 10
    cqo
    idiv rbx
    add rdx, 48
    mov [rsp + r10], dl
    inc r10
    mov r12, rax
    cmp rax, 0
    jne label_2
    cmp r13, 0
    je label_4
    mov byte [rsp+r10], 45
    inc r10
label_4:
    mov r8, 0
    mov r9, r10
    dec r9
label_5:
    cmp r8, r9
    jge label_6
    mov al, [rsp + r8]
    mov bl, [rsp + r9]
    mov [rsp + r8], bl
    mov [rsp + r9], al
    inc r8
    dec r9
    jmp label_5
label_6:
    mov byte [rsp + r10], 10
    inc r10
    mov rax, 0x2000004
    mov rdi, 1
    lea rsi, [rsp]
    mov rdx, r10
    syscall
    add rsp, 32
    mov rax, 0x2000001
    mov rdi, 0
    syscall
